sonar.projectKey=tredy-ai_dockerfiles
sonar.projectName=Tredy AI Dockerfiles
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.inclusions=**/Dockerfile,**/*.yml,**/*.yaml
sonar.exclusions=.git/**,.github/workflows/build-push.yaml

sonar.qualitygate.wait=true
